connection_id : 'connection_name'
table_name : 'table_name'
project_id : 'project_name'
view_name : 'json_view'
config_path : 'config.yml'
host: 'https://companyname.looker.com:19999/api/3.1/'
secret: 'client_secret'
token: 'client_id'
